### ISSUE TITLE
Rotating Cards and Perspective Cards (V 1.1.0) are broken on Safari + Chrome (Mac)

### ISSUE THREAD

**Issue by science-core** [creativetimofficial/ct-material-kit-pro#11]
This also happens on the components page, screenshots are taken from there:
http://demos.creative-tim.com/material-kit-pro/index.html#cards

**Hovering a Rotating Card**

Image Card
![bildschirmfoto 2017-04-15 um 23 03 01](https://cloud.githubusercontent.com/assets/20483377/25066806/93fc5696-2231-11e7-878f-d287ed823352.png)

Background Card
![bildschirmfoto 2017-04-15 um 23 03 18](https://cloud.githubusercontent.com/assets/20483377/25066812/b0f90b2c-2231-11e7-8acb-344ce4094213.png)

Dribble Card
![bildschirmfoto 2017-04-15 um 23 03 25](https://cloud.githubusercontent.com/assets/20483377/25066817/b9fd1e0c-2231-11e7-99de-22c934d6a250.png)

**Rotating a Manual Rotating Card:**

![bildschirmfoto 2017-04-15 um 23 03 39](https://cloud.githubusercontent.com/assets/20483377/25066829/0a3c2a3e-2232-11e7-8343-18ff4c70763f.png)

**Perspective Cards:**

Before reloading page (clear cache):
![bildschirmfoto 2017-04-15 um 23 03 45](https://cloud.githubusercontent.com/assets/20483377/25066833/2c0b1a76-2232-11e7-9c4f-3fa84864bc65.png)

After reloading page - I'm hovering the left card:
![bildschirmfoto 2017-04-15 um 23 13 50](https://cloud.githubusercontent.com/assets/20483377/25066839/525c5334-2232-11e7-962f-aea62e659f09.png)

Oh, by the way, Dynamic Shadows™ work well!

Thank you!

**Comment by alexandru-paduraru** [comment]
@science-core wow! It seems something si really wrong there :-O It seems some js methods are not called at the right time.

We will start investigating this and come with a solution for v1.1.1. Can you please let us know which version of Chrome you used? On our systems, the pointed issues are visible only in Safari V10.0 (12602.1.50.0.10). 

Best,
Alex

**Comment by science-core** [comment]
> Google Chrome, Version 57.0.2987.133 (64-bit)

**Comment by awakenedguy** [comment]
I confirm exactly the same problem on Windows as well, Chrome 58.0.3029.110 (64-bit), Windows 10. It happens all the time, when one enters the demo page for the first time (easy to recreate by deleting the browser cache + cookies, containing the word "creative"):
http://demos.creative-tim.com/material-kit-pro/index.html

Rotating cards + perspective cards are broken in 100% of the cases.

A subsequent refresh of the page fixes the problem and renders them working again.

**Comment by alexandru-paduraru** [comment]
@awakenedguy @science-core we've checked and it seems the cards are loading too fast, actually they are loading before the images, that's why they are getting a wrong size. To fix that, please go to line 64 in `assets/js/material-kit.js` and move this code outside of the `$(document).ready(...);` function

```js
//initialise rotating cards
materialKit.initRotateCard();

//initialise colored shadow
materialKit.initColoredShadows();

//initialise animation effect on images
materialKit.initAtvImg();
```

to a `$(window).on("load", function...)` function like this:

```js
$(window).on("load", function() {
     //initialise rotating cards
     materialKit.initRotateCard();

     //initialise colored shadow
     materialKit.initColoredShadows();

     //initialise animation effect on images
     materialKit.initAtvImg();
 });
```

Then everything will be activated as soon as all the images are loaded. Let us know if this was working fine.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Fixed in v1.1.1, please check it :D

**Comment by science-core** [comment]
Yes, but some rotating cards are still broken **in Safari**:

Dribble
TechCrunch
Fashion 
Background

![bildschirmfoto 2017-05-29 um 22 45 53](https://cloud.githubusercontent.com/assets/20483377/26561867/0213c080-44c2-11e7-837c-4cd8716be7c3.png)
![bildschirmfoto 2017-05-29 um 22 45 46](https://cloud.githubusercontent.com/assets/20483377/26561871/023d5d6e-44c2-11e7-8a31-f25ff14cad53.png)
![bildschirmfoto 2017-05-29 um 22 45 28](https://cloud.githubusercontent.com/assets/20483377/26561869/023b2d5a-44c2-11e7-9d93-35fa25af8c58.png)
![bildschirmfoto 2017-05-29 um 22 45 10](https://cloud.githubusercontent.com/assets/20483377/26561870/023cc908-44c2-11e7-9d13-9e1494e3db90.png)


Safari:
![bildschirmfoto 2017-05-29 um 22 46 15](https://cloud.githubusercontent.com/assets/20483377/26561879/10b20ebc-44c2-11e7-81b8-bbafa891615f.png)

**Comment by manzullo** [comment]
We are waiting for this to be solved please

**Comment by dragosct10** [comment]
Hi! Sorry for the late response. We find a solution for your problem and for fixing the issue please follow the next steps: 

1. First go in `assets/sass/material-kit/_cards.scss` and replace with the new one. 

[_cards.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/1155119/_cards.scss.zip)

2. Second go in `assets/js/material-kit.js` and inside of the javascript object `materialKit` find the `initRotateCard` function and inside of this function please add the following lines of code and then set the `debounce` of this function to `50`:  

```js
$('.rotating-card-container .card-rotate').each(function(){
    var $this = $(this);

    var card_width = $(this).parent().width();
    var card_height = $(this).find('.front .card-content').outerHeight();

    $this.parent().css({
        'height': card_height + 'px',
        'margin-bottom': 30 + 'px'
    });

    $this.find('.front').css({
         'height': card_height + 'px',
         'width': card_width + 'px',
    });

    $this.find('.back').css({
        'height': card_height + 'px',
         'width': card_width + 'px',
    });
});
```

3. In the html page `index.html` please search for the tags `div` with classes `.card .card-rotate .card-background` and inside of this find the tag `div` with class `.front` and add the class `.front-background`.

4. After you do that please compile your scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/material-kit.css`.

Please let us know if everything is working fine! 

Regards,
Dragos

**Comment by manzullo** [comment]
I can't do it. Is there an update in the theme ?

**Comment by dragosct10** [comment]
Hi @manzullo! Yes, it will be an update in August, but tell me where did you get stucked and I will try  to help you to achieve this modifications. 

Regards,
Dragos

**Comment by manzullo** [comment]
Hi @dragosct10 thank you. 

I can't undestand where in the 2. step i have to put the code. 

In step 3. I applied material kit to a wp template and i think i don't have to modify the index.html as described but change the code in my wp output. Am I right?

In step 4. I don't know how to use Koala and what does it mean complice a css. I don't know the steps to do these things

**Comment by dragosct10** [comment]
Hi @manzullo! Ok I will update for you the `material-kit.js` so now you don't have to make all the modifications from the step number `2`, just take the uploaded file and replace in `assets/js/material-kit.js`.

[material-kit.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1161971/material-kit.js.zip)

For the step 3 yes, you have right you must make the modifications in your wp output.

Now, below I will show you the steps to compile the scss with [Koala](koala-app.com): 

     1. Add the SASS folder from assets/sass/ to a new project inside Koala Compiler and find the file material-kit.scss, it will be the one in Green.

     2. Right click on that file and set the output path, it must be in assets/css/ so anything that you compile will overwrite the original material-kit.css.

     3. Press on compile and everything will be done automatically.

**Comment by manzullo** [comment]
Ok, i did everything, the rotating card no more disappear after rotating but the output is not so good:

I replaced  <div class="front"> with div class="front front-background"> you can see it on https://www.comeout.it

**Comment by dragosct10** [comment]
Hi @manzullo! I looked over your project and I noticed that you don't have the same html structure of the cards like in `MK Pro`. I will show you below the differences between our structure of cards and yours, but to understand better what I say please go in `MK Pro` in `index.html` at the `Morphing Cards` section to see exactly. Now, you have the structure of the cards like this: 

<img width="643" alt="screen shot 2017-07-21 at 12 21 16" src="https://user-images.githubusercontent.com/17456857/28457538-2c512c18-6e0f-11e7-9aad-cdcc98fb5f90.png">

What is wrong here is that you have inserted the div with class `.card-image` in the div with class `.front`. In the `MK Pro` the structure look like this: 

<img width="932" alt="screen shot 2017-07-21 at 12 26 24" src="https://user-images.githubusercontent.com/17456857/28457716-e30cab4e-6e0f-11e7-88d0-e9fe2494f512.png">

So the main reason of how looks your cards now is that you don't have the same html structure like in `MK Pro`, please follow our html structure and I hope everything will work fine. Please let us know if everything is working fine! 

Regards,
Dragos

**Comment by manzullo** [comment]
I would like to put the image in a manual rotating card, before it worked fine, the only problem was that after rotating the back of the content became blank.

**Comment by dragosct10** [comment]
Hi @manzullo! Yes you have right, before it worked for you because the `scss` for rotating cards was not changed, but now to resolve this issue we have made modifications in the `scss` so the structure must be like in `MK Pro`. 

Regards,
Dragos

**Comment by manzullo** [comment]
Ok, but adding front-background it styles as grey

**Comment by manzullo** [comment]
And on mobile the back button after rotating is not centered

**Comment by manzullo** [comment]
Hi, i'm still waiting to use this product. I was waiting to this release to be updated in the download section, so to not be constraicted to modify code i'm not able to. I still have the problems i wrote on july: front-background is grey, back button not centered after rotanting (on mobile)

**Comment by alexandru-paduraru** [comment]
@manzullo if you add the style with background-image on the div with `.front` class everything will work fine.

Please check it here:

<img width="1045" alt="screen shot 2017-09-01 at 11 05 46" src="https://user-images.githubusercontent.com/2517758/29960762-a361eede-8f05-11e7-9410-f37893dcb645.png">

Hope this helps.

Best,
Alex
