### ISSUE TITLE
navbar-expand appears inconsistantly

### ISSUE THREAD

**Issue by chrisjenx** [creativetimofficial/ct-material-kit-pro#75]
If you use anything but navbar-expand-lg the the navbar-items and the navbar-toggler appear and disappear at different times.

**Comment by chrisjenx** [comment]
Can replicate on firefox with this code:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Welcome</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="Stylesheet" type="text/css" href="static/css/material-kit.min.css">
  </head>
  <body class="landing-page">
    <nav class="navbar navbar-color-on-scroll navbar-transparent fixed-top navbar-expand-md" color-on-scroll="100" id="sectionsNav">
      <div class="container">
        <div class="navbar-translate"><a href="/" class="navbar-brand">BCJ Networks</a><button type="button" class="navbar-toggler" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span><span class="navbar-toggler-icon"></span><span class="navbar-toggler-icon"></span></button></div>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active"><a href="/" class="nav-link">Home<span class="sr-only">(current)</span></a></li>
            <li class="nav-item"><a href="/pricing" class="nav-link">Pricing</a></li>
            <li class="nav-item"><a href="/about" class="nav-link">About Us</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="page-header header-filter" data-paralax="true">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1 class="title">Welcome to your personal internet provider</h1>
            <div>Widgets are much easier!</div>
          </div>
        </div>
      </div>
    </div>
    <script src="static/js/jquery-3.3.1.min.js"></script>
    <script src="static/js/popper.min.js"></script>
    <script src="static/js/bootstrap-material-design.min.js"></script>
    <script src="static/js/material-kit.min.js?v=2.0.2"></script>
  </body>
</html>
```

**Comment by dragosct10** [comment]
Hi, @chrisjenx! Thank you for using our product. Do you want to use the navbar with the class navbar-expand-MD? Regards, Dragos

**Comment by dragosct10** [comment]
Hi! You are right about it and we will check this and we will come with a fix. Regards, Dragos

**Comment by chrisjenx** [comment]
OK great! Thanks.

**Comment by chrisjenx** [comment]
Looks like this was fixed in 2.0.3?

**Comment by dragosct10** [comment]
Hi! Yes, this is fixed in the version 2.0.3. Regards, Dragos

**Comment by 4levels** [comment]
Hi, this issue still seems to exist in the free version.. 
I'm using version 2.0.3 and when using any other navbar-expand-* than the documented -lg version, the collapse button doesn't respect this.
